### PR TITLE
Use name of versioned package in import aliases

### LINKED ISSUE #17: Docs don’t work when using import::from('pkg (>=1.0)', ...)
Using the versioned form of `import::from`, upon trying to fetch the help of an item, `import` tries to fetch the docs for `` `pkg (>=1.0)`::item`` instead of `pkg::item`:

```r
> import::from('pkg (>=1.0)', item)
> ?item
import: showing documentation for `pkg (>=1.0)`::item

Error in find.package(if (is.null(package)) loadedNamespaces() else package, :
there is no package called ‘pkg (>=1.0)’
...
```

### PR DESCRIPTION
**Pull request by flying-sheep**
Fixes #17

### CODE REVIEW

**Comment by flying-sheep** [comment]
hello?

**Comment by flying-sheep** [comment]
anyone alive?

**Comment by smbache** [comment]
Thanks.

**Comment by flying-sheep** [comment]
No problem!

**Pull request merged**
